services:
  db:
    container_name: appdelanta_local_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

  backend:
    container_name: appdelanta_local_backend
    ports:
      - "8001:8000"

volumes:
  postgres_local_data:
