# Generated by Django 5.2.13 on 2026-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='company',
            name='chamber_of_commerce_document',
            field=models.FileField(blank=True, help_text='Documento PDF de cámara de comercio', null=True, upload_to='chamber_of_commerce/', verbose_name='Cámara de Comercio (PDF)'),
        ),
    ]
