# Generated by Django 5.2.14 on 2026-05-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_employee_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIT/RUT'),
        ),
    ]
